
# @name tokenAPI
POST http://localhost:3001/api/v1/auth/register
Content-Type: application/json

{
    "email": "testuser22@gmail.com",
    "username": "testuser22",
    "password": "testuser22",
    "confirmPassword": "testuser22",
    "referralCode": "ref-ghunx6g7"
}


####

# Login
# @name tokenAPI
POST http://localhost:3001/api/v1/auth/login
Content-Type: application/json

{
    "email": "kolaiwalewa@gmail.com",
    "password": "kola0522"
}

####

@authToken = {{tokenAPI.response.body.token}}
# Get User
# @name getUser
GET http://localhost:3001/api/v1/user/
Content-Type: application/json
Authorization: Bearer {{authToken}}

######

GET http://localhost:3001/api/v1/user/all

######


GET http://localhost:3001/api/v1/user/6722378793c4a7a80e68aa7c

####
GET http://localhost:3001/api/v1/inventory/6722512f61a01729e67bc375


######

POST http://localhost:3001/api/v1/subscription/subscribe
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhMzhmYmI1YzNlMzVhNGViZTAyNGEiLCJpYXQiOjE3MzA3MTE0NDYsImV4cCI6MTc2MjI2OTA0Nn0.6jDN--Nr6MyOa-OqVVzD0oPWH7E2Ajus40HqShZcjO8

{
    "planId": "65dc534815ce9430aa0ab115"
}

######

GET http://localhost:3001/api/v1/subscription/plan

######


POST http://localhost:3001/api/v1/whatsapp-otp/generate
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhMzhmYmI1YzNlMzVhNGViZTAyNGEiLCJpYXQiOjE3MzA3MTE0NDYsImV4cCI6MTc2MjI2OTA0Nn0.6jDN--Nr6MyOa-OqVVzD0oPWH7E2Ajus40HqShZcjO8


######

GET http://localhost:3001/api/v1/ping/ping

######



GET http://localhost:3001/api/v1/user/profile/kolawole-iwalewa

#####

GET http://localhost:3001/api/v1/user/complete-profiles

####

GET http://localhost:3001/api/v1/user/shareable-link/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhMzhmY2I1YzNlMzVhNGViZTAyNGMiLCJpYXQiOjE3MzE5MDc3NDAsImV4cCI6MTc2MzQ2NTM0MH0.D5eYOo548OZcUIm0w3XoWSHs0aHzEHmdFO-GPqlo2dM

#####

GET http://localhost:3001/api/v1/subscription/subscriptions

######

POST http://localhost:3001/api/v1/subscription/webhook

######

GET http://localhost:3001/api/v1/user/profile/kolawole-iwalewa

#####

GET http://localhost:3001/api/v1/user/static-complete-profiles

#####

GET http://localhost:3001/api/v1/user/top-12-sellers

######

GET http://64.176.179.24/api/v1/user/complete-profiles

######


https://api.joinsafelink.com/api/v1/user/all


######

POST http://localhost:3001/api/v1/subscription/cancel
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhMzhmY2I1YzNlMzVhNGViZTAyNGMiLCJpYXQiOjE3MzE5MDc3NDAsImV4cCI6MTc2MzQ2NTM0MH0.D5eYOo548OZcUIm0w3XoWSHs0aHzEHmdFO-GPqlo2dM

#####


POST http://localhost:3001/api/v1/subscription/manual-subscription
Content-Type: application/json

{
    "id": "asd",
    "reference": "ab33389e-8eb6-4c74-bb14-42fe67532fc3"
}

######

POST https://safelink.up.railway.app/add_inventory_to_ai
Content-Type: application/json

{
    "inventory_id": "66faf5eab0d7086885949951"
}

#####

POST http://localhost:3001/api/v1/influencer/create-influencer
Content-Type: application/json

{
    "name": "Akinolu Ololade Salimo",
    "referralCode": "sally"
}

#####


GET http://localhost:3001/api/v1/referral/current-month/subscribed


#####


GET https://api.joinsafelink.com/api/v1/referral/current-month/subscribed

#####

@authToken = {{tokenAPI.response.body.token}}
POST http://localhost:3001/api/v1/referral/create-referral
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NmNhMzhmY2I1YzNlMzVhNGViZTAyNGMiLCJpYXQiOjE3MzU2NTE5NjEsImV4cCI6MTc2NzIwOTU2MX0.ofrsMzOTLXzB1eQAgb-58PD15CPunLfp1J6eSWMqc6M

{
    "accountName": "Iwalewa Kolawole",
    "bankName": "GT Bank",
    "accountNumber": "0441800394",
    "bankCode": "000013"
}